server:
  port: 8762

spring:
  application:
    name: eureka-server

eureka:
  instance:
    status-page-url-path: /actuator/health  # 상태 페이지 경로
    health-check-url-path: /actuator/health  # 상태 체크 경로
    hostname: eureka2
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/,http://127.0.0.1:8763/eureka/
    registerWithEureka: true
    fetchRegistry: true
#  server:
#    # Eureka 서버가 "self preservation" 모드를 비활성화합니다.
#    # 이를 통해 클라이언트가 등록 해제될 때 바로 반영됩니다. (실제 운영 환경에서는 이 설정을 켜두는 것이 좋습니다.)
#    enableSelfPreservation: false