server:
  port: 9090

spring:
  application:
    name: api-gateway  # Eureka에 등록될 서비스 이름

  cloud:
    gateway:
      routes:
        - id: time-service1  # 라우팅 ID
          uri: lb://TIME-SERVICE1  # Eureka에서 `time-service` 이름으로 서비스를 찾아서 요청을 전달
          predicates:
            - Path=/time-service1/**  # "/time-service/**" 경로로 들어오는 요청을 라우팅
          filters:
            - RewritePath=/time-service1/(?<path>.*),/$\{path}
            - name: "Retry"
              args:
                retries: 3
                statuses: INTERNAL_SERVER_ERROR
        - id: time-service2  # 라우팅 ID
          uri: lb://TIME-SERVICE2  # Eureka에서 `time-service` 이름으로 서비스를 찾아서 요청을 전달
          predicates:
            - Path=/time-service2/**  # "/time-service/**" 경로로 들어오는 요청을 라우팅
          filters:
            - RewritePath=/time-service2/(?<path>.*),/$\{path}
            - name: "Retry"
              args:
                retries: 3
                statuses: INTERNAL_SERVER_ERROR

eureka:
  client:
    register-with-eureka: false
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/  # Eureka 서버 URL