server:
  port: 8081

spring:
  application:
    name: time-service2  # Eureka에 등록될 서비스 이름

# springboot actuator 설정
management:
  endpoints:
    web:
      exposure:
        include: health, info # open 할 actuator 경로 설정
  endpoint:
    health:
      show-details: always # actuator/health 에 디테일 정보 반환
  info:
    os:
      enabled: true
    java:
      enabled: true
    env:
      enabled: true

# springboot actuator info 에 표시될 정보 설정
info:
  made-by: com.rayllylinker

# eureka 서버에 전달할 정보 설정
eureka:
  instance:
    hostname: localhost
  client:
    # Eureka Client 로 등록
    register-with-eureka: true
    # Eureka 서버에서 레지스트리를 가져올지 여부
    fetch-registry: false
    healthcheck:
      enabled: true  # Eureka 서버가 /actuator/health 엔드포인트로 상태를 확인
    service-url:
      # Eureka 서버 목록
      defaultZone: http://127.0.0.1:8761/eureka/,http://127.0.0.1:8762/eureka/,http://127.0.0.1:8763/eureka/