server:
  port: 8761

spring:
  application:
    name: eureka-server

eureka:
  instance:
    status-page-url-path: /actuator/health  # 상태 페이지 경로
    health-check-url-path: /actuator/health  # 상태 체크 경로
    hostname: 127.0.0.1
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
    # Eureka 서버가 클라이언트로 동작하지 않도록 설정
    registerWithEureka: false
    fetchRegistry: false
#  server:
#    # Eureka 서버가 "self preservation" 모드를 비활성화합니다.
#    # 이를 통해 클라이언트가 등록 해제될 때 바로 반영됩니다. (실제 운영 환경에서는 이 설정을 켜두는 것이 좋습니다.)
#    enableSelfPreservation: false